version: 2

jobs:
  all:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i
            npm run bootstrap:ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - run:
          name: Configure deployment
          command: |
            static_s3_base="s3://cf-apps-static/apps-test-$CIRCLE_SHA1"
            test "$CIRCLE_BRANCH" == 'master' && static_s3_base='s3://cf-apps-static/apps'
            echo "export STATIC_S3_BASE=\"$static_s3_base\"" >> $BASH_ENV

            static_jira_s3_base="s3://cf-apps-static/apps-test-$CIRCLE_SHA1/jira"
            test "$CIRCLE_BRANCH" == 'master' && static_jira_s3_base='s3://cf-apps-jira'
            echo "export STATIC_JIRA_S3_BASE=\"$static_jira_s3_base\"" >> $BASH_ENV

            stage='test'
            test "$CIRCLE_BRANCH" == 'master' && stage='prd'
            echo "export STAGE=\"$stage\"" >> $BASH_ENV

            source "$BASH_ENV"
            echo "Static deployment S3 base: $STATIC_S3_BASE"
            echo "Static Jira deployment S3 base: $STATIC_JIRA_S3_BASE"
            echo "API Gateway stage: $STAGE"
      - run:
          name: Install pip
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy apps
          command: npm run deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - all
