version: 2
# Required secret environment variables
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

jobs:
  test:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - run:
          name: Configure deployment
          command: |
            static_bucket='cf-apps-static-test'
            test "$CIRCLE_BRANCH" == 'master' && static_bucket='cf-apps-static'
            echo "export STATIC_BUCKET=\"$static_bucket\"" >> $BASH_ENV
            stage='test'
            test "$CIRCLE_BRANCH" == 'master' && stage='prd'
            echo "export STAGE=\"$stage\"" >> $BASH_ENV
            source "$BASH_ENV"
            echo "Static deployment bucket: $STATIC_BUCKET"
            echo "API Gateway stage: $STAGE"

  deploy:
    docker:
      - image: circleci/node:10-stretch
        environment:
          STATIC_APPS_BUCKET: s3://cf-apps-static
    steps:
      - checkout
      - run:
          name: Install pip
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install dependencies
          command: |
            npm i
      - run:
          name: 'Deploy apps'
          command: npm run deploy -- --concurrency=1

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
